version: '3'

services:
  startserver:
    build: .
    ports:
      - "3000:3000"
    command: startserver
    volumes:
      - ./files:/root/files
  nutella:
    build: .
    volumes:
      - ./files:/root/files